namespace BitwardenExportPrint
{
    runtimeclass PasswordElement
    {
        PasswordElement(String description, String username, String password);

        String description{ get; };
        String username{ get; };
        String password{ get; };
    }
}