import "MainPage.idl";
import "PasswordElement.idl";

namespace BitwardenExportPrint
{
    [default_interface]
    runtimeclass PasswordPrintPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PasswordPrintPage(MainPage main_page, UInt32 page_number);
        void UpdateData(UInt32 value);
        UInt32 page_number{ get; };
        UInt32 final_page_number{ get; };
        Windows.Foundation.DateTime now{ get; };
                
        Windows.Foundation.Collections.IObservableVector<PasswordElement> password_elements{ get; };
    }
}
