import "MainPage.idl";
import "PasswordElement.idl";

namespace BitwardenExportPrint
{
    [default_interface]
    runtimeclass PasswordPrintPage : Windows.UI.Xaml.Controls.Page
    {
        PasswordPrintPage(MainPage main_page, UInt32 page_number);
        
        Windows.Foundation.Collections.IObservableVector<PasswordElement> password_elements{ get; };
    }
}
